### PR TITLE
Impl `StripPrefixWriter` in mod `writer`

### PR DESCRIPTION
**Pull request by NobodyXu**
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Review by jaywonchung — APPROVED** [review]
Perfect! I also like your decision of reporting the stripped bytes as "written".

LGTM. Thank you!

**Comment by NobodyXu** [comment]
> Perfect! I also like your decision of reporting the stripped bytes as "written".

It has to be, otherwise it will write part of the `buf` again.

**Comment by jaywonchung** [comment]
Aha. Just tested it myself and saw tests failing haha. Basically the return value is more like "the number of bytes consumed from the buffer".

**Comment by NobodyXu** [comment]
Yes.

I also made the same mistakes before and thanks to the unit tests, I was able to fix it.

**Pull request merged**
